spring:
    application:
        name: 02-Mini-Project

    datasource:
        url: jdbc:mysql://localhost:3306/Courses
        username: root
        password: Ray@2002
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: true

server:
    port: 4041
